@echo off
setlocal EnableExtensions EnableDelayedExpansion

cd /d "%~dp0"

set "DATA_DIR=%LOCALAPPDATA%\Pebblegram"
set "ENV_FILE=%DATA_DIR%\pebblegram.env"
set "NGROK_CONFIG=%DATA_DIR%\ngrok.yml"
set "VENV_PY=.venv\Scripts\python.exe"

if not exist "%DATA_DIR%" mkdir "%DATA_DIR%"

where py >nul 2>nul
if %ERRORLEVEL%==0 (
  set "PY=py -3"
) else (
  where python >nul 2>nul
  if %ERRORLEVEL%==0 (
    set "PY=python"
  ) else (
    echo Python was not found.
    echo Install Python for your user account, then run dockerless.bat again.
    echo https://www.python.org/downloads/windows/
    pause
    exit /b 1
  )
)

if not exist "%VENV_PY%" (
  echo Creating local Python environment...
  %PY% -m venv .venv
  if errorlevel 1 goto fail
)

echo Installing helper dependencies...
"%VENV_PY%" -m pip install --upgrade pip
if errorlevel 1 goto fail
"%VENV_PY%" -m pip install telethon==1.43.2 "Pillow>=9.1,<12"
if errorlevel 1 goto fail

if not exist "%ENV_FILE%" (
  echo.
  echo Pebblegram dockerless setup
  echo Create Telegram API credentials at https://my.telegram.org/apps
  echo.
  set /p TELEGRAM_API_ID=Telegram API ID: 
  set /p TELEGRAM_API_HASH=Telegram API hash: 
  set /p TELEGRAM_PHONE=Telegram phone number: 
  for /f "usebackq delims=" %%T in (`"%VENV_PY%" -c "import secrets; print(secrets.token_hex(24))"`) do set "PEBBLEGRAM_TOKEN=%%T"

  > "%ENV_FILE%" echo # Generated by Pebblegram dockerless.bat
  >> "%ENV_FILE%" echo TELEGRAM_API_ID=!TELEGRAM_API_ID!
  >> "%ENV_FILE%" echo TELEGRAM_API_HASH=!TELEGRAM_API_HASH!
  >> "%ENV_FILE%" echo TELEGRAM_PHONE=!TELEGRAM_PHONE!
  >> "%ENV_FILE%" echo TELEGRAM_SESSION=%DATA_DIR%\pebblegram
  >> "%ENV_FILE%" echo TELEGRAM_ALLOW_READ_CONTENT=1
  >> "%ENV_FILE%" echo TELEGRAM_ALLOW_SEND=1
  >> "%ENV_FILE%" echo TELEGRAM_ALLOW_DELETE=0
  >> "%ENV_FILE%" echo PEBBLEGRAM_TOKEN=!PEBBLEGRAM_TOKEN!
  echo.
  echo Saved settings to %ENV_FILE%
  echo Use this bridge token in Pebblegram settings:
  echo !PEBBLEGRAM_TOKEN!
  echo.
)

set "NGROK_CMD="
if exist "%~dp0ngrok.exe" (
  set "NGROK_CMD=%~dp0ngrok.exe"
) else (
  for /f "delims=" %%N in ('where ngrok 2^>nul') do (
    if not defined NGROK_CMD set "NGROK_CMD=%%N"
  )
)

set "NGROK_READY=0"
if defined NGROK_CMD (
  if exist "%NGROK_CONFIG%" (
    findstr /c:"authtoken:" "%NGROK_CONFIG%" >nul 2>nul
    if not errorlevel 1 set "NGROK_READY=1"
  )
  if "!NGROK_READY!"=="0" (
    echo.
    echo Ngrok setup
    echo Create or copy your authtoken from https://dashboard.ngrok.com/get-started/your-authtoken
    echo Press Enter to skip ngrok and use a LAN/VPN bridge URL instead.
    set /p NGROK_AUTHTOKEN=Ngrok authtoken: 
    if not "!NGROK_AUTHTOKEN!"=="" (
      "!NGROK_CMD!" config add-authtoken "!NGROK_AUTHTOKEN!" --config "%NGROK_CONFIG%"
      if errorlevel 1 goto fail
    )
  )
  if exist "%NGROK_CONFIG%" (
    findstr /c:"authtoken:" "%NGROK_CONFIG%" >nul 2>nul
    if not errorlevel 1 set "NGROK_READY=1"
  )
) else (
  echo.
  echo ngrok.exe was not found next to dockerless.bat or on PATH.
  echo Install ngrok from https://ngrok.com/download to get a public HTTPS bridge URL.
  echo The helper will still run locally on http://localhost:8765.
)

for /f "usebackq tokens=1,* delims==" %%A in (`findstr /v /b "#" "%ENV_FILE%"`) do (
  if not "%%A"=="" set "%%A=%%B"
)

set "PEBBLEGRAM_DATA_DIR=%DATA_DIR%"

echo.
echo Starting Pebblegram helper without Docker.
echo Leave this window open while using Pebblegram.
echo Local settings page: http://localhost:8765/config.html
echo.

if "%NGROK_READY%"=="1" (
  start "Pebblegram Bridge" cmd /k ""%VENV_PY%" tools\bridge.py --mode telegram --host 0.0.0.0 --port 8765"
  timeout /t 2 /nobreak >nul
  start "Pebblegram ngrok" cmd /k ""!NGROK_CMD!" http 8765 --config "%NGROK_CONFIG%" --log=stdout"
  echo Check the Pebblegram ngrok window for the public https URL.
  echo You can also open http://127.0.0.1:4040 to copy it.
  echo Use that URL and the bridge token in Pebblegram settings.
  echo.
  echo The bridge and ngrok are running in separate windows.
  pause
) else (
  "%VENV_PY%" tools\bridge.py --mode telegram --host 0.0.0.0 --port 8765
  if errorlevel 1 goto fail
)
exit /b 0

:fail
echo.
echo Pebblegram dockerless helper failed.
pause
exit /b 1
