#!/usr/bin/env python3
from __future__ import annotations

import os
import secrets
import sys
from pathlib import Path


ENV_FILE = Path(os.environ.get("PEBBLEGRAM_ENV_FILE", "/data/pebblegram.env"))
REQUIRED = ("TELEGRAM_API_ID", "TELEGRAM_API_HASH", "TELEGRAM_PHONE")


def load_env_file() -> None:
    if not ENV_FILE.exists():
        return
    for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        if not os.environ.get(key):
            os.environ[key] = value


def prompt(name: str, label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{label}{suffix}: ").strip()
    return value or default


def write_env_file(values: dict[str, str]) -> None:
    ENV_FILE.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by Pebblegram first-run setup.",
        f"TELEGRAM_API_ID={values['TELEGRAM_API_ID']}",
        f"TELEGRAM_API_HASH={values['TELEGRAM_API_HASH']}",
        f"TELEGRAM_PHONE={values['TELEGRAM_PHONE']}",
        f"TELEGRAM_SESSION={values['TELEGRAM_SESSION']}",
        f"TELEGRAM_ALLOW_READ_CONTENT={values['TELEGRAM_ALLOW_READ_CONTENT']}",
        f"TELEGRAM_ALLOW_SEND={values['TELEGRAM_ALLOW_SEND']}",
        f"TELEGRAM_ALLOW_DELETE={values['TELEGRAM_ALLOW_DELETE']}",
        f"PEBBLEGRAM_TOKEN={values['PEBBLEGRAM_TOKEN']}",
        "",
    ]
    ENV_FILE.write_text("\n".join(lines), encoding="utf-8")
    ENV_FILE.chmod(0o600)


def ensure_setup() -> None:
    load_env_file()
    missing = [name for name in REQUIRED if not os.environ.get(name)]
    if not missing:
        return

    if not sys.stdin.isatty():
        missing_text = ", ".join(missing)
        print(
            f"Missing {missing_text}. Run this container interactively once, "
            f"or mount {ENV_FILE} with Telegram credentials.",
            file=sys.stderr,
        )
        sys.exit(2)

    print("Pebblegram bridge first-run setup")
    print("Create Telegram API credentials at https://my.telegram.org/apps")
    values = {
        "TELEGRAM_API_ID": os.environ.get("TELEGRAM_API_ID") or prompt("TELEGRAM_API_ID", "Telegram API ID"),
        "TELEGRAM_API_HASH": os.environ.get("TELEGRAM_API_HASH") or prompt("TELEGRAM_API_HASH", "Telegram API hash"),
        "TELEGRAM_PHONE": os.environ.get("TELEGRAM_PHONE") or prompt("TELEGRAM_PHONE", "Telegram phone number"),
        "TELEGRAM_SESSION": os.environ.get("TELEGRAM_SESSION", "/data/pebblegram"),
        "TELEGRAM_ALLOW_READ_CONTENT": os.environ.get("TELEGRAM_ALLOW_READ_CONTENT", "1"),
        "TELEGRAM_ALLOW_SEND": os.environ.get("TELEGRAM_ALLOW_SEND", "1"),
        "TELEGRAM_ALLOW_DELETE": os.environ.get("TELEGRAM_ALLOW_DELETE", "0"),
        "PEBBLEGRAM_TOKEN": os.environ.get("PEBBLEGRAM_TOKEN") or secrets.token_hex(24),
    }
    write_env_file(values)
    os.environ.update(values)
    print(f"Saved bridge settings to {ENV_FILE}")
    print("Use this bridge token in the Pebblegram settings page:")
    print(values["PEBBLEGRAM_TOKEN"])
    print("Telegram may ask for a login code next.")


def main() -> None:
    ensure_setup()
    argv = sys.argv[1:] or [
        "python",
        "tools/bridge.py",
        "--mode",
        "telegram",
        "--host",
        "0.0.0.0",
        "--port",
        "8765",
    ]
    os.execvp(argv[0], argv)


if __name__ == "__main__":
    main()
