#!/usr/bin/env python3
"""Regenerate tools/pebbleos-emoji-coverage.json from a PebbleOS checkout.

Run inside a full-history clone of https://github.com/coredevices/PebbleOS:
    python3 tools/extract-pebbleos-emoji.py /path/to/PebbleOS > tools/pebbleos-emoji-coverage.json

For each firmware tier it records which emoji the watch can draw: codepoints
that PebbleOS routes to its emoji font (codepoint_is_emoji) and that the font
actually contains, plus the non-ASCII glyphs of the Gothic fonts the app uses.
A tier only claims a glyph if every sampled release in it has that glyph.
"""
import json, re, struct, subprocess, sys

REPO = sys.argv[1] if len(sys.argv) > 1 else '.'
TIERS = {
    # PebbleOS 4.29.0 added ~1,200 Noto emoji to the system emoji fonts.
    'new': {'minFirmware': '4.29.0', 'revs': ['v4.29.0', 'v4.38.0', 'HEAD']},
    'old': {'minFirmware': '0.0.0', 'revs': ['55ac7aa05', 'b46135c43', 'bd5029d7a', 'v4.28.0']},
}
APP_FONTS = ['GOTHIC_14', 'GOTHIC_14_BOLD', 'GOTHIC_18', 'GOTHIC_18_BOLD', 'GOTHIC_24_BOLD']


def show(rev, path):
    return subprocess.run(['git', '-C', REPO, 'show', f'{rev}:{path}'], capture_output=True).stdout


def pbf_codepoints(data):
    if data[0] >= 3:
        _, _, num, _, hsz, cpb, fis, feat = struct.unpack_from('<BBHHBBBB', data, 0)
    else:
        _, _, num, _, hsz, cpb = struct.unpack_from('<BBHHBB', data, 0)
        fis, feat = 8, 0
    size = cpb + (2 if feat & 1 else 4)
    start = fis + hsz * 4
    return {int.from_bytes(data[start + i * size:start + i * size + cpb], 'little') for i in range(num)}


def emoji_font(rev):
    return set.intersection(*[pbf_codepoints(show(rev, f'resources/normal/base/pbf/EMOJI_{s}.pbf'))
                              for s in (14, 18, 24, 28)])


def router(rev):
    src = show(rev, 'src/fw/applib/fonts/codepoint.c').decode()
    names = {m[0]: int(m[1], 16) for m in re.findall(r'#define (\w+)_CODEPOINT\s+(0x[0-9A-Fa-f]+)', src)}
    listed = re.search(r'NONSTANDARD_EMOJI_CODEPOINTS\[\] = \{(.*?)\};', src, re.S).group(1)
    listed = {int(x, 16) for x in re.findall(r'0x[0-9A-Fa-f]+', listed)}
    body = re.search(r'bool codepoint_is_emoji\(.*?\n\}', src, re.S).group(0)
    spans = [(names[a], names[b]) for a, b in
             re.findall(r'codepoint >= (\w+)_CODEPOINT\s*&&\s*codepoint <= (\w+)_CODEPOINT', body)]
    return lambda cp: cp in listed or any(a <= cp <= b for a, b in spans)


def gothic(rev):
    files = {}
    for path in ('resources/common/base/resource_map.json', 'resources/normal/base/resource_map.json'):
        raw = show(rev, path)
        if raw:
            for media in json.loads(raw)['media']:
                if media.get('type') == 'font':
                    files[media['name']] = media['file']
    return set.intersection(*[pbf_codepoints(show(rev, 'resources/' + files[n])) for n in APP_FONTS])


def ranges(values):
    out = []
    for cp in sorted(values):
        if out and out[-1][1] == cp - 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


result = {'_comment': 'Generated by tools/extract-pebbleos-emoji.py from coredevices/PebbleOS.', 'tiers': {}}
for name, tier in TIERS.items():
    emoji = gothic_cps = None
    routed = set()
    for rev in tier['revs']:
        is_emoji = router(rev)
        e = {cp for cp in emoji_font(rev) if is_emoji(cp)}
        g = {cp for cp in gothic(rev) if cp >= 0x80}
        emoji = e if emoji is None else emoji & e
        gothic_cps = g if gothic_cps is None else gothic_cps & g
        routed |= {cp for cp in range(0x80, 0x20000) if is_emoji(cp)}
    result['tiers'][name] = {'minFirmware': tier['minFirmware'], 'emoji': ranges(emoji),
                             'gothic': ranges(gothic_cps), 'routed': ranges(routed)}
json.dump(result, sys.stdout, separators=(',', ':'))
